### ISSUE TITLE
connection-user should be connection-password in data-engineer doc

### ISSUE THREAD

**Issue by prabhacloud** [starburstdata/starburstdata.github.io#6]
The SQL Connector config needs to be updated in https://docs.starburst.io/data-engineer/index.html similar to https://docs.starburst.io/latest/connector/sqlserver.html#configuration

**Comment by Ordinant** [comment]
@prabhacloud, thank you so much for this report and issue 7. Both are being fixed in the source today, and should appear on the public site sometime Monday, US daytime hours.

Please keep telling us about issues like this.
