### ISSUE TITLE
broken link in data engineer doc

### ISSUE THREAD

**Issue by prabhacloud** [starburstdata/starburstdata.github.io#7]
I was going through the doc https://docs.starburst.io/data-engineer/index.html#how-does-this-work  to learn more about the product and when clicked on migration guide it open a page https://docs.starburst.io/latest/migration/from-hive.html with 404.

**Comment by Ordinant** [comment]
@prabhacloud, thank you so much for this report and issue 6. Both are being fixed in the source today, and should appear on the public site sometime Monday, US daytime hours.

Please keep telling us about issues like this.
